"""LED dance floor generator — extends the floor generator with RGB tile lighting.

The dance floor is built on top of the base floor system.  A plain floor slab
is generated first, then a grid of coloured LED panels is overlaid on the
surface to create the disco/club look.  Each panel can be individually
coloured; the default palette cycles through rainbow hues.

Variations:
    checkerboard  — alternating lit / unlit black tiles (classic 70s look)
    rainbow_grid  — every tile a different hue cycling through the spectrum
    pulse_ring    — concentric rings of colour emanating from center
"""

from generators.base import BaseAssetGenerator
from generators.style import AssetStyle

# Re-use the floor generator for the structural slab
from generators.floor import generate as floor_generate, DEFAULT_CFG as FLOOR_DEFAULT_CFG

DEFAULT_CFG = {
    # Slab dimensions (passed through to floor generator)
    "width": 6.0,
    "length": 6.0,
    "depth": 0.1,
    # LED tile grid
    "tile_size": 0.5,        # size of each square LED tile
    "tile_gap": 0.01,        # gap between tiles
    "tile_depth": 0.012,     # raised thickness of each tile panel
    "glow_strength": 4.0,    # emission strength for lit tiles
    "variation": "rainbow_grid",  # "checkerboard" | "rainbow_grid" | "pulse_ring"
}

# Rainbow palette for tiles (RGBA)
RAINBOW_PALETTE = [
    (1.00, 0.05, 0.05, 1.0),   # red
    (1.00, 0.45, 0.00, 1.0),   # orange
    (1.00, 1.00, 0.00, 1.0),   # yellow
    (0.00, 0.90, 0.10, 1.0),   # green
    (0.00, 0.45, 1.00, 1.0),   # blue
    (0.55, 0.00, 1.00, 1.0),   # violet
]


def generate(config=None, style=None):
    """Generate an LED dance floor.

    Args:
        config: dict — dimension and style overrides; accepts all DEFAULT_CFG keys.
        style:  AssetStyle for the slab material (tiles use hardcoded emission).

    Returns:
        The primary Blender object (joined mesh).
    """
    cfg = dict(DEFAULT_CFG)
    cfg.update(config or {})
    if style is None:
        style = AssetStyle(theme="modern", material="tile", wear=0.2)
    from . import mesh
    return mesh.create_dance_floor(cfg, style)


class DanceFloorGenerator(BaseAssetGenerator):
    """OOP wrapper for the LED dance floor.

    Extends the base floor system: the slab geometry is generated by the
    existing ``generators.floor`` module; this class adds the LED tile grid
    on top.

    Example::

        gen = DanceFloorGenerator(config={"width": 8.0, "variation": "checkerboard"})
        obj = gen.generate()
    """

    DEFAULT_CFG = DEFAULT_CFG  # reference module-level dict

    def _default_style(self):
        return AssetStyle(theme="modern", material="tile", wear=0.2)

    def generate(self):
        from . import mesh
        return mesh.create_dance_floor(self.cfg, self.style)
